[theme]
primaryColor = "#15866f"
backgroundColor = "#f4f6f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#182126"
font = "sans serif"

[server]
headless = true
fileWatcherType = "none"
runOnSave = false

[browser]
gatherUsageStats = false
